eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:1950661299orange.com@master.eureka.com:8001/eureka/,http://admin:1950661299orange.com@slave.eureka.com:8002/eureka/

server:
  port: 8003
