spring:
  redis:
    host: 39.101.162.9
    password: g1008611m@
    port: 6379
    jedis:
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1
    database: 1
    timeout: 5000