server:
  port: 8002

#配置双注册中心
eureka:
  instance:
    instance-id: orange-eureka-02    #自定义服务名称信息
    hostname: slave.eureka.com
    appname: orange-eureka-server
  client:
    serviceUrl:
      defaultZone: http://admin:1950661299orange.com@master.eureka.com:8001/eureka/
