server:
  port: 9000

eureka:
  instance:
    instance-id: orange-gateway    #自定义服务名称信息
    appname: orange-gateway
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://admin:1950661299orange.com@master.eureka.com:8001/eureka/,http://admin:1950661299orange.com@slave.eureka.com:8002/eureka/

info:
  app.name: orange-gateway
  company.name: www.orangewangke.cn
  build.artifactId: @project.artifactId@
  build.version: @project.version@

spring:
  cloud:
    #设置路由规则
    gateway:
      routes:
        - id: gateway-manager
          uri: lb://ORANGE-MANAGER-WEB        #代表从注册中心获取服务，且以lb(load-balance)负载均衡方式转发
          predicates:                     #断言
            - Path=/admin/**            #表示将以/service01/**开头的请求转发到uri为lb://MICROSERVICE01的地址上
          filters:
            - StripPrefix=1                #表示将Path的路径/service01在转发前去掉，如果设置StripPrefix=2，表示将/service01/*去掉 以此类推... 同时将spring.cloud.gateway.discovery.locator.enabled改为false，如果不改的话，之前的localhost:8799/client01/test01这样的请求地址也能正常访问，因为这时为每个服务创建了2个router

        - id: gateway-search
          uri: lb://ORANGE-CONSUMER-SEARCH        #代表从注册中心获取服务，且以lb(load-balance)负载均衡方式转发
          predicates:                     #断言
            - Path=/**            #表示将以/service01/**开头的请求转发到uri为lb://MICROSERVICE01的地址上
#          filters:
#            - StripPrefix=1                #表示将Path的路径/service01在转发前去掉，如果设置StripPrefix=2，表示将/service01/*去掉 以此类推... 同时将spring.cloud.gateway.discovery.locator.enabled改为false，如果不改的话，之前的localhost:8799/client01/test01这样的请求地址也能正常访问，因为这时为每个服务创建了2个router

      discovery:
        locator:
          #表示gateway开启服务注册和发现功能,
          #并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，这个router将以服务名开头的请求路径转发到对应的服务
          enabled: false
          #表示将请求路径的服务名配置改成小写  因为服务注册的时候，向注册中心注册时将服务名转成大写的了
          lower-case-service-id: true